apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: zomato
          image: kapilbtech86/zomato:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32385

